server:
  port: 8080

spring:
  application:
    name: order
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: username
    password:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  data:
    redis:
      host: localhost
      port: 6379